/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WLVManagementSoftware;

import javax.swing.*;
import java.io.*;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Siddhartha
 */
public class StudentReport extends javax.swing.JFrame {
    ArrayList<StudentDetail> studentDetailArrayList=new ArrayList<>();

    /**
      Creates new form StudentReport
     */
    public StudentReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportarea = new javax.swing.JTextArea();
        M1txt = new javax.swing.JTextField();
        m1mark = new javax.swing.JTextField();
        m2txt = new javax.swing.JTextField();
        m2mark = new javax.swing.JTextField();
        m3txt = new javax.swing.JTextField();
        m3mark = new javax.swing.JTextField();
        m4txt = new javax.swing.JTextField();
        m4mark = new javax.swing.JTextField();
        m5txt = new javax.swing.JTextField();
        m5mark = new javax.swing.JTextField();
        m6txt = new javax.swing.JTextField();
        m6mark = new javax.swing.JTextField();
        totaltxt = new javax.swing.JTextField();
        percentagetxt = new javax.swing.JTextField();
        garadetxt = new javax.swing.JTextField();
        calcbtn = new javax.swing.JButton();
        generatebtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Students_grade_updated = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Student Name:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Course Name:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Module 1: Marks");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Module3: Marks");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Moduel 5: Marks");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Module 6: Marks");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Module 2: Marks");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Module 4: Marks");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Total Marks");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Grade");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("percentage");

        reportarea.setColumns(20);
        reportarea.setRows(5);
        jScrollPane1.setViewportView(reportarea);

        m1mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1markActionPerformed(evt);
            }
        });

        m3txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3txtActionPerformed(evt);
            }
        });

        m5txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5txtActionPerformed(evt);
            }
        });

        m6txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6txtActionPerformed(evt);
            }
        });

        m6mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6markActionPerformed(evt);
            }
        });

        totaltxt.setActionCommand("<Not Set>");

        percentagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentagetxtActionPerformed(evt);
            }
        });

        garadetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garadetxtActionPerformed(evt);
            }
        });

        calcbtn.setText("Print Report");
        calcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcbtnActionPerformed(evt);
            }
        });

        generatebtn.setText("Genarate Card");
        generatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebtnActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Id");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Admin");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Student ");

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        Students_grade_updated.setColumns(20);
        Students_grade_updated.setRows(5);
        jScrollPane2.setViewportView(Students_grade_updated);

        jButton1.setText("View Teacher's Grading Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel10)
                                                                                        .addComponent(jLabel11)
                                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(53, 53, 53)
                                                                                                .addComponent(calcbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(percentagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(garadetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                        .addComponent(generatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                                                                        .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(M1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(m1mark, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(17, 17, 17)
                                                                                                .addComponent(jLabel3)))
                                                                                .addGap(42, 42, 42)
                                                                                .addComponent(m5txt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(m5mark, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                .addComponent(m4txt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(55, 55, 55))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabel9)
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                        .addGap(164, 164, 164)
                                                                                                        .addComponent(m4mark, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addGap(53, 53, 53)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(m2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(m2mark, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(jLabel8)
                                                                                        .addComponent(jLabel5))
                                                                                .addGap(45, 45, 45)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(jLabel7)
                                                                                        .addComponent(jLabel4)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(m3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(m3mark))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(m6txt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(m6mark, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(271, 271, 271)
                                                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(61, 61, 61)
                                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(83, 83, 83)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel13)
                                                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel1)
                                                                                .addGap(139, 139, 139)
                                                                                .addComponent(jLabel2)))
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jLabel12)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2))
                                .addGap(428, 428, 428))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel13))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jTextField3)
                                                                .addGap(5, 5, 5))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(M1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(m1mark)
                                                        .addComponent(m2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(m2mark)
                                                        .addComponent(m3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(m3mark))
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel5))
                                                .addGap(7, 7, 7)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(m4txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(m4mark)
                                                        .addComponent(m6txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(m6mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(m5txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(m5mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(calcbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(percentagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(generatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel15))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(garadetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))
                                                .addGap(338, 338, 338))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(325, 325, 325))))
        );

        pack();
    }// </editor-fold>

    private void m6txtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void m1markActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void m3txtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void m5txtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void m6markActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void percentagetxtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void garadetxtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void calcbtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String fname=jTextField1.getText();
        String id=jTextField2.getText();
        String cname=jTextField3.getText();
        String m1=M1txt.getText();
        String m2=m2txt.getText();
        String m3=m3txt.getText();
        String m4=m4txt.getText();
        String m5=m5txt.getText();
        String m6=m6txt.getText();
        String ma1=m1mark.getText();
        String ma2=m2mark.getText();
        String ma3=m3mark.getText();
        String ma4=m4mark.getText();
        String ma5=m5mark.getText();
        String ma6=m6mark.getText();
        String total=totaltxt.getText();
        String percentage=percentagetxt.getText();
        String grade=garadetxt.getText();

        studentDetailArrayList.add(new StudentDetail(fname,id,cname,m1,m2,m3,m4,m5,m6,ma1,ma2,ma3,ma4,ma5,ma6,total,percentage,grade));
        for (int i = 0; i <studentDetailArrayList.size(); i++) {
            Object[] objs={studentDetailArrayList.get(i).fname,studentDetailArrayList.get(i).id,
                    studentDetailArrayList.get(i).cname,

                    studentDetailArrayList.get(i).mod1,
                    studentDetailArrayList.get(i).m1,

                    studentDetailArrayList.get(i).mod2,
                    studentDetailArrayList.get(i).m2,

                    studentDetailArrayList.get(i).mod3,
                    studentDetailArrayList.get(i).m3,

                    studentDetailArrayList.get(i).mod4,
                    studentDetailArrayList.get(i).m4,

                    studentDetailArrayList.get(i).mod5,
                    studentDetailArrayList.get(i).m5,

                    studentDetailArrayList.get(i).mod6,
                    studentDetailArrayList.get(i).m6,

                    studentDetailArrayList.get(i).total,
                    studentDetailArrayList.get(i).percentage,
                    studentDetailArrayList.get(i).grade
            };

        }
        try{
            File file = new File("stsReport.txt");
            FileWriter fileWriter= new FileWriter(file);
            Writer storage=new BufferedWriter(fileWriter);
            int size=studentDetailArrayList.size();
            for (int i = 0; i <size ; i++) {
                storage.write("\n\n"+"\t\t\t\t\t.........................................."+"\n\n\n\n"
                        +studentDetailArrayList.get(i).fname+
                        "\n"+
                        studentDetailArrayList.get(i).id+
                        "\n"+
                        studentDetailArrayList.get(i).cname+
                        "\n"+
                        studentDetailArrayList.get(i).mod1+
                        ":\t"+
                        studentDetailArrayList.get(i).m1+
                        "\n"+
                        studentDetailArrayList.get(i).mod2+
                        ":\t"+
                        studentDetailArrayList.get(i).m2+
                        "\n"+
                        studentDetailArrayList.get(i).mod3+
                        ":\t"+
                        studentDetailArrayList.get(i).m3+
                        "\n"+
                        studentDetailArrayList.get(i).mod4+
                        ":\t"+
                        studentDetailArrayList.get(i).m4+
                        "\n"+
                        studentDetailArrayList.get(i).mod5+
                        ":\t"+
                        studentDetailArrayList.get(i).m5+
                        "\n"+
                        studentDetailArrayList.get(i).mod6+
                        "\n"+
                        studentDetailArrayList.get(i).total+
                        "\t"+
                        studentDetailArrayList.get(i).percentage+
                        "\t"+
                        studentDetailArrayList.get(i).grade
                );

            }
            storage.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        try{
            reportarea.print();
        }
        catch (Exception e){

        }
        JOptionPane.showMessageDialog(null,"Report stored in stsReport.txt");
    }

    private void generatebtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:


        //Generating Report Card
        reportarea.setText("******************************************************************************\n");
        reportarea.setText(reportarea.getText()+"                          University of Wolverhampton             \n");
        reportarea.setText(reportarea.getText()+"************************************************************************");

        Date obj = new Date();
        String date =obj.toString();

        reportarea.setText(reportarea.getText()+"\n"+date+"\n");
        reportarea.setText(reportarea.getText()+"\nStudent name: "+jTextField1.getText()+"\t"+
                            "Course: "+jTextField2.getText()+"\t"+"Id:"+jTextField3.getText()+"\n");
        reportarea.setText(reportarea.getText()+M1txt.getText()+":"+m1mark.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+m2txt.getText()+":"+m2mark.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+m3txt.getText()+":"+m3mark.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+m4txt.getText()+":"+m4mark.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+m5txt.getText()+":"+m5mark.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+m6txt.getText()+":"+m6mark.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+"Total Marks: "+totaltxt.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+"Percentage:"+percentagetxt.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+"Grade:"+garadetxt.getText()+"\n\n");
        reportarea.setText(reportarea.getText()+"                                                                 Signature");

        if(garadetxt.getText()=="A"||garadetxt.getText()=="a"||garadetxt.getText()=="a"||
                garadetxt.getText()=="B"||garadetxt.getText()=="b"||
                garadetxt.getText()=="B+"||garadetxt.getText()=="b+"||
                garadetxt.getText()=="C"||garadetxt.getText()=="c"||
                garadetxt.getText()=="C+"||garadetxt.getText()=="c+"||
                garadetxt.getText()=="D+"||garadetxt.getText()=="d+")
        {
            reportarea.setText(reportarea.getText() + "\t\t\t******PASS Goodluck*******\n\n");
        }

        else{
            reportarea.setText(reportarea.getText() + "\t\t\t******Failed Goodluck*******\n\n");

        }
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        m2txt.setText("");
        m2mark.setText("");
        m3txt.setText("");
        m3mark.setText("");
        m4txt.setText("");
        m4mark.setText("");
        m5mark.setText("");
        m5mark.setText("");
        m6txt.setText("");
        m6mark.setText("");
        totaltxt.setText("");
        percentagetxt.setText("");
        garadetxt.setText("");
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        String filename= "student_grades.txt";
        try{
            FileReader reader=new FileReader(filename);
            BufferedReader br= new BufferedReader(reader);
            Students_grade_updated.read(br,null);
            br.close();
            Students_grade_updated.requestFocus();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField M1txt;
    private javax.swing.JTextArea Students_grade_updated;
    private javax.swing.JButton calcbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField garadetxt;
    private javax.swing.JButton generatebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField m1mark;
    private javax.swing.JTextField m2mark;
    private javax.swing.JTextField m2txt;
    private javax.swing.JTextField m3mark;
    private javax.swing.JTextField m3txt;
    private javax.swing.JTextField m4mark;
    private javax.swing.JTextField m4txt;
    private javax.swing.JTextField m5mark;
    private javax.swing.JTextField m5txt;
    private javax.swing.JTextField m6mark;
    private javax.swing.JTextField m6txt;
    private javax.swing.JTextField percentagetxt;
    private javax.swing.JTextArea reportarea;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration
}
