@startuml

title __BASE's Class Diagram__\n

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.Array {
            # data : Data
            + addValue()
            + getData()
            + setData()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.Data {
            # value : List<Value>
            + addValue()
            + getValue()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.Fault {
            # value : Value
            + getValue()
            + setValue()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.Member {
            # name : String
            # value : Value
            + Member()
            + Member()
            + getName()
            + getValue()
            + setName()
            + setValue()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.MethodCall {
            # methodName : String
            # params : Params
            + getMethodName()
            + getParams()
            + setMethodName()
            + setParams()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.MethodResponse {
            # fault : Fault
            # params : Params
            + getFault()
            + getParams()
            + setFault()
            + setParams()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.Param {
            # value : Value
            + Param()
            + Param()
            + getValue()
            + setValue()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.Params {
            # param : List<Param>
            + addParam()
            + getParam()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.ResponseParser {
            ~ elNames : Stack<Object>
            ~ objects : Stack<Object>
            - resp : MethodResponse
            + characters()
            + endElement()
            + getMethodResponse()
            + startElement()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.Struct {
            # member : List<Member>
            + addMember()
            + getMember()
            + toString()
        }
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace xmlrpc {
      namespace base {
        class com.mysql.fabric.xmlrpc.base.Value {
            {static} + TYPE_array : byte
            {static} + TYPE_base64 : byte
            {static} + TYPE_boolean : byte
            {static} + TYPE_dateTime_iso8601 : byte
            {static} + TYPE_double : byte
            {static} + TYPE_i4 : byte
            {static} + TYPE_int : byte
            {static} + TYPE_string : byte
            {static} + TYPE_struct : byte
            # objType : byte
            # objValue : Object
            - dtf : DatatypeFactory
            + Value()
            + Value()
            + Value()
            + Value()
            + Value()
            + Value()
            + Value()
            + Value()
            + Value()
            + appendString()
            + getType()
            + getValue()
            + setArray()
            + setBase64()
            + setBoolean()
            + setBoolean()
            + setDateTime()
            + setDateTime()
            + setDouble()
            + setDouble()
            + setInt()
            + setInt()
            + setString()
            + setStruct()
            + toString()
            - escapeXMLChars()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
