@startuml

title __INTERCEPTORS's Class Diagram__\n

  namespace com.mysql.jdbc {
    namespace interceptors {
      class com.mysql.jdbc.interceptors.ResultSetScannerInterceptor {
          # regexP : Pattern
          + destroy()
          + executeTopLevelOnly()
          + init()
          + postProcess()
          + preProcess()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace interceptors {
      class com.mysql.jdbc.interceptors.ServerStatusDiffInterceptor {
          - postExecuteValues : Map<String, String>
          - preExecuteValues : Map<String, String>
          + destroy()
          + executeTopLevelOnly()
          + init()
          + postProcess()
          + preProcess()
          - populateMapWithSessionStatusValues()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace interceptors {
      class com.mysql.jdbc.interceptors.SessionAssociationInterceptor {
          # currentSessionKey : String
          {static} # sessionLocal : ThreadLocal<String>
          + destroy()
          + executeTopLevelOnly()
          {static} + getSessionKey()
          + init()
          + postProcess()
          + preProcess()
          {static} + resetSessionKey()
          {static} + setSessionKey()
      }
    }
  }
  

  com.mysql.jdbc.interceptors.ResultSetScannerInterceptor .up.|> StatementInterceptor
  com.mysql.jdbc.interceptors.ServerStatusDiffInterceptor .up.|> StatementInterceptor
  com.mysql.jdbc.interceptors.SessionAssociationInterceptor .up.|> StatementInterceptor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
