@startuml

title __JDBC42's Class Diagram__\n

  namespace testsuite {
    namespace simple {
      namespace jdbc4 {
        namespace  {
          class testsuite.simple.jdbc42.ConnectionTest {
              + ConnectionTest()
              + testDriverAcceptsURLNullArgument()
              + testDriverConnectNullArgument()
              + testDriverConnectPropertiesPrecedence()
              + testSupportsRefCursors()
          }
        }
      }
    }
  }
  

  namespace testsuite {
    namespace simple {
      namespace jdbc4 {
        namespace  {
          class testsuite.simple.jdbc42.ResultSetTest {
              + ResultSetTest()
              + testNonUpdResultSetUpdateObject()
              + testUpdResultSetUpdateObjectAndNewSupportedTypes()
              + testUpdResultSetUpdateObjectAndNewUnsupportedTypes()
          }
        }
      }
    }
  }
  

  namespace testsuite {
    namespace simple {
      namespace jdbc4 {
        namespace  {
          class testsuite.simple.jdbc42.StatementsTest {
              - testDateString : String
              - testDateTimeString : String
              - testISODateTimeString : String
              - testLocalDate : LocalDate
              - testLocalDateTime : LocalDateTime
              - testLocalTime : LocalTime
              - testOffsetDateTime : OffsetDateTime
              - testOffsetTime : OffsetTime
              - testSqlDate : Date
              - testSqlTime : Time
              - testSqlTimeStamp : Timestamp
              - testTimeString : String
              + StatementsTest()
              + testCallStmtExecuteLargeBatch()
              + testCallStmtExecuteLargeUpdate()
              + testCallStmtRegisterOutParameter()
              + testCallStmtRegisterOutParameterNewUnsupportedTypes()
              + testCallStmtSetObjectAndNewSupportedTypes()
              + testCallStmtSetObjectAndNewUnsupportedTypes()
              + testPrepStmtExecuteLargeBatch()
              + testPrepStmtExecuteLargeUpdateExplicitGeneratedKeys()
              + testPrepStmtExecuteLargeUpdateNoGeneratedKeys()
              + testPrepStmtSetObjectAndNewSupportedTypes()
              + testPrepStmtSetObjectAndNewUnsupportedTypes()
              + testServPrepStmtSetObjectAndNewSupportedTypes()
              + testServPrepStmtSetObjectAndNewUnsupportedTypes()
              + testServerPrepStmtExecuteLargeBatch()
              + testSharedTestData()
              + testStmtExecuteLargeBatch()
              + testStmtExecuteLargeUpdate()
              + testStmtExecuteLargeUpdateNoGeneratedKeys()
              + testStmtGetSetLargeMaxRows()
              - checkUnsupportedTypesBehavior()
              - insertTestDataLocalDTTypes()
              - insertTestDataOffsetDTTypes()
              - validateTestDataLocalDTTypes()
              - validateTestDataOffsetDTTypes()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
