@startuml

title __PROFILER's Class Diagram__\n

  namespace com.mysql.jdbc {
    namespace profiler {
      class com.mysql.jdbc.profiler.LoggingProfilerEventHandler {
          - log : Log
          + LoggingProfilerEventHandler()
          + consumeEvent()
          + destroy()
          + init()
          + processEvent()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace profiler {
      class com.mysql.jdbc.profiler.ProfilerEvent {
          {static} + NA : byte
          {static} + TYPE_EXECUTE : byte
          {static} + TYPE_FETCH : byte
          {static} + TYPE_OBJECT_CREATION : byte
          {static} + TYPE_PREPARE : byte
          {static} + TYPE_QUERY : byte
          {static} + TYPE_SLOW_QUERY : byte
          {static} + TYPE_USAGE : byte
          {static} + TYPE_WARN : byte
          + catalogIndex : int
          + eventCreationPointIndex : int
          + hostNameIndex : int
          # catalog : String
          # connectionId : long
          # durationUnits : String
          # eventCreationPointDesc : String
          # eventCreationTime : long
          # eventDuration : long
          # eventType : byte
          # hostName : String
          # message : String
          # resultSetId : int
          # statementId : int
          + ProfilerEvent()
          + getCatalog()
          + getConnectionId()
          + getDurationUnits()
          + getEventCreationPointAsString()
          + getEventCreationTime()
          + getEventDuration()
          + getEventType()
          + getHostName()
          + getMessage()
          + getResultSetId()
          + getStatementId()
          + pack()
          + toString()
          {static} + unpack()
          - ProfilerEvent()
          {static} - readBytes()
          {static} - readInt()
          {static} - readLong()
          {static} - writeBytes()
          {static} - writeInt()
          {static} - writeLong()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace profiler {
      interface com.mysql.jdbc.profiler.ProfilerEventHandler {
          {abstract} + consumeEvent()
          {abstract} + processEvent()
      }
    }
  }
  

  com.mysql.jdbc.profiler.LoggingProfilerEventHandler .up.|> ProfilerEventHandler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
