@startuml

title __JDBC's Class Diagram__\n

  namespace testsuite {
    namespace fabric {
      namespace jdbc {
        class testsuite.fabric.jdbc.TestBasicConnection {
            + TestBasicConnection()
            + testConnectionDataSource()
            + testConnectionUrl()
        }
      }
    }
  }
  

  namespace testsuite {
    namespace fabric {
      namespace jdbc {
        class testsuite.fabric.jdbc.TestFabricMySQLConnectionSharding {
            - conn : FabricMySQLConnection
            - ds : FabricMySQLDataSource
            + TestFabricMySQLConnectionSharding()
            + setUp()
            + tearDown()
            + testGlobalTableCreation()
            + testQueryTableShardSelection()
            + testQueryTablesPreventCrossShardQuery()
            + testShardSelection()
        }
      }
    }
  }
  

  namespace testsuite {
    namespace fabric {
      namespace jdbc {
        class testsuite.fabric.jdbc.TestHABasics {
            - conn : FabricMySQLConnection
            - ds : FabricMySQLDataSource
            - masterPort : String
            + TestHABasics()
            + manualTestFailedOldMasterDoesntBlockNewConnections()
            + manualTestFailedSingleSlaveDoesntBlockNewConnections()
            + manualTestFailover()
            + manualTestNewConnHasNewState()
            + setUp()
            + tearDown()
            + testReadWriteSplitting()
            - getPort()
        }
      }
    }
  }
  

  namespace testsuite {
    namespace fabric {
      namespace jdbc {
        class testsuite.fabric.jdbc.TestHashSharding {
            - conn : FabricMySQLConnection
            - ds : FabricMySQLDataSource
            + TestHashSharding()
            + checkRowDoesntExistInKeyGroup()
            + setUp()
            + tearDown()
            + testBasicInsertByGroup()
            + testBasicInsertByKey()
            # assertBasicDataIsInProperPlaces()
            # checkRowDoesntExist()
            # checkRowDoesntExistInServerGroup()
            # checkRowExists()
            # checkRowExistsInKeyGroup()
            # checkRowExistsInServerGroup()
        }
      }
    }
  }
  

  namespace testsuite {
    namespace fabric {
      namespace jdbc {
        class testsuite.fabric.jdbc.TestRegressions {
            - conn : FabricMySQLConnection
            + TestRegressions()
            + manualTestBug22750465()
            + manualTestRefreshFabricStateCache()
            + testBug21876798()
            + testBug73070()
            + testBug75080()
            + testBug77217()
            + testBug82094()
            - manualTestBug22750465SomeReadWriteOperations()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
