@startuml

title __AUTHENTICATION's Class Diagram__\n

  namespace com.mysql.jdbc {
    namespace authentication {
      class com.mysql.jdbc.authentication.CachingSha2PasswordPlugin {
          {static} + PLUGIN_NAME : String
          + destroy()
          + getProtocolPluginName()
          + init()
          + nextAuthenticationStep()
          + reset()
          # encryptPassword()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace authentication {
      enum AuthStage {
        FAST_AUTH_COMPLETE
        FAST_AUTH_READ_RESULT
        FAST_AUTH_SEND_SCRAMBLE
        FULL_AUTH
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace authentication {
      class com.mysql.jdbc.authentication.MysqlClearPasswordPlugin {
          - connection : Connection
          - password : String
          + destroy()
          + getProtocolPluginName()
          + init()
          + isReusable()
          + nextAuthenticationStep()
          + requiresConfidentiality()
          + reset()
          + setAuthenticationParameters()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace authentication {
      class com.mysql.jdbc.authentication.MysqlNativePasswordPlugin {
          - connection : Connection
          - password : String
          + destroy()
          + getProtocolPluginName()
          + init()
          + isReusable()
          + nextAuthenticationStep()
          + requiresConfidentiality()
          + reset()
          + setAuthenticationParameters()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace authentication {
      class com.mysql.jdbc.authentication.MysqlOldPasswordPlugin {
          - connection : Connection
          - password : String
          + destroy()
          + getProtocolPluginName()
          + init()
          + isReusable()
          + nextAuthenticationStep()
          + requiresConfidentiality()
          + reset()
          + setAuthenticationParameters()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace authentication {
      class com.mysql.jdbc.authentication.Sha256PasswordPlugin {
          {static} + PLUGIN_NAME : String
          # connection : Connection
          # password : String
          # publicKeyRequested : boolean
          # publicKeyString : String
          # seed : String
          + destroy()
          + getProtocolPluginName()
          + init()
          + isReusable()
          + nextAuthenticationStep()
          + requiresConfidentiality()
          + reset()
          + setAuthenticationParameters()
          # encryptPassword()
          # encryptPassword()
          {static} - readRSAKey()
      }
    }
  }
  

  com.mysql.jdbc.authentication.CachingSha2PasswordPlugin o-- com.mysql.jdbc.authentication.CachingSha2PasswordPlugin.AuthStage : stage
  com.mysql.jdbc.authentication.CachingSha2PasswordPlugin +-down- com.mysql.jdbc.authentication.CachingSha2PasswordPlugin.AuthStage
  com.mysql.jdbc.authentication.MysqlClearPasswordPlugin .up.|> AuthenticationPlugin
  com.mysql.jdbc.authentication.MysqlNativePasswordPlugin .up.|> AuthenticationPlugin
  com.mysql.jdbc.authentication.MysqlOldPasswordPlugin .up.|> AuthenticationPlugin
  com.mysql.jdbc.authentication.Sha256PasswordPlugin .up.|> AuthenticationPlugin


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
