@startuml

title __JMX's Class Diagram__\n

  namespace com.mysql.jdbc {
    namespace jmx {
      class com.mysql.jdbc.jmx.LoadBalanceConnectionGroupManager {
          - isJmxRegistered : boolean
          + LoadBalanceConnectionGroupManager()
          + addHost()
          + getActiveHostCount()
          + getActiveHostsList()
          + getActiveLogicalConnectionCount()
          + getActivePhysicalConnectionCount()
          + getRegisteredConnectionGroups()
          + getTotalHostCount()
          + getTotalLogicalConnectionCount()
          + getTotalPhysicalConnectionCount()
          + getTotalTransactionCount()
          + registerJmx()
          + removeHost()
          + stopNewConnectionsToHost()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace jmx {
      interface com.mysql.jdbc.jmx.LoadBalanceConnectionGroupManagerMBean {
          {abstract} + addHost()
          {abstract} + getActiveHostCount()
          {abstract} + getActiveHostsList()
          {abstract} + getActiveLogicalConnectionCount()
          {abstract} + getActivePhysicalConnectionCount()
          {abstract} + getRegisteredConnectionGroups()
          {abstract} + getTotalHostCount()
          {abstract} + getTotalLogicalConnectionCount()
          {abstract} + getTotalPhysicalConnectionCount()
          {abstract} + getTotalTransactionCount()
          {abstract} + removeHost()
          {abstract} + stopNewConnectionsToHost()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace jmx {
      class com.mysql.jdbc.jmx.ReplicationGroupManager {
          - isJmxRegistered : boolean
          + addSlaveHost()
          + getActiveLogicalConnectionCount()
          + getActiveMasterHostCount()
          + getActiveSlaveHostCount()
          + getMasterHostsList()
          + getRegisteredConnectionGroups()
          + getSlaveHostsList()
          + getSlavePromotionCount()
          + getTotalLogicalConnectionCount()
          + promoteSlaveToMaster()
          + registerJmx()
          + removeMasterHost()
          + removeSlaveHost()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace jmx {
      interface com.mysql.jdbc.jmx.ReplicationGroupManagerMBean {
          {abstract} + addSlaveHost()
          {abstract} + getActiveLogicalConnectionCount()
          {abstract} + getActiveMasterHostCount()
          {abstract} + getActiveSlaveHostCount()
          {abstract} + getMasterHostsList()
          {abstract} + getRegisteredConnectionGroups()
          {abstract} + getSlaveHostsList()
          {abstract} + getSlavePromotionCount()
          {abstract} + getTotalLogicalConnectionCount()
          {abstract} + promoteSlaveToMaster()
          {abstract} + removeMasterHost()
          {abstract} + removeSlaveHost()
      }
    }
  }
  

  com.mysql.jdbc.jmx.LoadBalanceConnectionGroupManager .up.|> LoadBalanceConnectionGroupManagerMBean
  com.mysql.jdbc.jmx.ReplicationGroupManager .up.|> ReplicationGroupManagerMBean


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
