@startuml

title __UTIL's Class Diagram__\n

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.Base64Decoder {
          {static} - decoderMap : byte[]
          {static} + decode()
          {static} - getNextValidByte()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.Base64Decoder.IntWrapper {
          + value : int
          + IntWrapper()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      abstract class com.mysql.jdbc.util.BaseBugReport {
          - conn : Connection
          - driver : Driver
          + BaseBugReport()
          + getConnection()
          + getConnection()
          + getConnection()
          + getNewConnection()
          + getUrl()
          + run()
          {abstract} + runTest()
          {abstract} + setUp()
          {abstract} + tearDown()
          # assertTrue()
          # assertTrue()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.ErrorMappingsDocGenerator {
          {static} + main()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.LRUCache {
          # maxElements : int
          {static} - serialVersionUID : long
          + LRUCache()
          # removeEldestEntry()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.PropertiesDocGenerator {
          {static} ~ serialVersionUID : long
          {static} + main()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.ReadAheadInputStream {
          # currentPosition : int
          # doDebug : boolean
          # endOfCurrentData : int
          # log : Log
          {static} - DEFAULT_BUFFER_SIZE : int
          - buf : byte[]
          - underlyingStream : InputStream
          + ReadAheadInputStream()
          + ReadAheadInputStream()
          + available()
          + close()
          + markSupported()
          + read()
          + read()
          + skip()
          - checkClosed()
          - fill()
          - readFromUnderlyingStreamIfNecessary()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.ResultSetUtil {
          {static} + appendResultSetSlashGStyle()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.ServerController {
          {static} + BASEDIR_KEY : String
          {static} + DATADIR_KEY : String
          {static} + DEFAULTS_FILE_KEY : String
          {static} + EXECUTABLE_NAME_KEY : String
          {static} + EXECUTABLE_PATH_KEY : String
          - serverProcess : Process
          - serverProps : Properties
          - systemProps : Properties
          + ServerController()
          + ServerController()
          + forceStop()
          + getServerProps()
          + setBaseDir()
          + setDataDir()
          + start()
          + stop()
          - buildOptionalCommandLine()
          - getCommandLine()
          - getFullExecutablePath()
          - getSystemProperties()
          - isNonCommandLineArgument()
          - runningOnWindows()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.TimezoneDump {
          {static} - DEFAULT_URL : String
          + TimezoneDump()
          {static} + main()
      }
    }
  }
  

  namespace com.mysql.jdbc {
    namespace util {
      class com.mysql.jdbc.util.VersionFSHierarchyMaker {
          {static} + main()
          {static} + removeWhitespaceChars()
          {static} - usage()
      }
    }
  }
  

  com.mysql.jdbc.util.Base64Decoder +-down- com.mysql.jdbc.util.Base64Decoder.IntWrapper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
