@startuml

title __XMLRPC's Class Diagram__\n

  namespace com.mysql.fabric {
    namespace proto.xmlrpc {
      class com.mysql.fabric.proto.xmlrpc.AuthenticatedXmlRpcMethodCaller {
          - password : String
          - underlyingCaller : XmlRpcMethodCaller
          - url : String
          - username : String
          + AuthenticatedXmlRpcMethodCaller()
          + call()
          + clearHeader()
          + setHeader()
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace proto.xmlrpc {
      class com.mysql.fabric.proto.xmlrpc.DigestAuthentication {
          {static} - random : Random
          {static} + calculateMD5RequestDigest()
          {static} + generateAuthorizationHeader()
          {static} + generateCnonce()
          {static} + getChallengeHeader()
          {static} + parseDigestChallenge()
          {static} + serializeDigestResponse()
          {static} - checksumMD5()
          {static} - digestMD5()
          {static} - hexEncode()
          {static} - quoteParam()
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace proto.xmlrpc {
      class com.mysql.fabric.proto.xmlrpc.InternalXmlRpcMethodCaller {
          - xmlRpcClient : Client
          + InternalXmlRpcMethodCaller()
          + call()
          + clearHeader()
          + setHeader()
          - methodResponseArrayToList()
          - unwrapValue()
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace proto.xmlrpc {
      class com.mysql.fabric.proto.xmlrpc.ResultSetParser {
          + ResultSetParser()
          + parse()
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace proto.xmlrpc {
      class com.mysql.fabric.proto.xmlrpc.XmlRpcClient {
          {static} - FIELD_ADDRESS : String
          {static} - FIELD_COLUMN_NAME : String
          {static} - FIELD_GLOBAL_GROUP_ID : String
          {static} - FIELD_GROUP_ID : String
          {static} - FIELD_HOST : String
          {static} - FIELD_LOWER_BOUND : String
          {static} - FIELD_MAPPING_ID : String
          {static} - FIELD_MODE : String
          {static} - FIELD_PORT : String
          {static} - FIELD_RESULT : String
          {static} - FIELD_SCHEMA_NAME : String
          {static} - FIELD_SERVER_UUID : String
          {static} - FIELD_SHARD_ID : String
          {static} - FIELD_STATUS : String
          {static} - FIELD_TABLE_NAME : String
          {static} - FIELD_TYPE_NAME : String
          {static} - FIELD_WEIGHT : String
          {static} - METHOD_DUMP_FABRIC_NODES : String
          {static} - METHOD_DUMP_SERVERS : String
          {static} - METHOD_DUMP_SHARD_INDEX : String
          {static} - METHOD_DUMP_SHARD_MAPS : String
          {static} - METHOD_DUMP_SHARD_TABLES : String
          {static} - METHOD_GROUP_ADD : String
          {static} - METHOD_GROUP_CREATE : String
          {static} - METHOD_GROUP_DESTROY : String
          {static} - METHOD_GROUP_LOOKUP_GROUPS : String
          {static} - METHOD_GROUP_PROMOTE : String
          {static} - METHOD_GROUP_REMOVE : String
          {static} - METHOD_SHARDING_ADD_SHARD : String
          {static} - METHOD_SHARDING_ADD_TABLE : String
          {static} - METHOD_SHARDING_CREATE_DEFINITION : String
          {static} - METHOD_SHARDING_LOOKUP_SERVERS : String
          {static} - METHOD_THREAT_REPORT_ERROR : String
          {static} - METHOD_THREAT_REPORT_FAILURE : String
          {static} - THREAT_REPORTER_NAME : String
          - methodCaller : XmlRpcMethodCaller
          + XmlRpcClient()
          + addServerToGroup()
          + createGroup()
          + createServerInGroup()
          + createShardIndex()
          + createShardMapping()
          + createShardTable()
          + destroyGroup()
          + getFabricNames()
          + getGroupNames()
          + getServerGroup()
          + getServerGroups()
          + getServerGroups()
          + getServersForKey()
          + getShardMappings()
          + getShardMappings()
          + promoteServerInGroup()
          + removeServerFromGroup()
          + reportServerError()
          - errorSafeCallMethod()
          - getShardIndices()
          - getShardTables()
          {static} - toServerSet()
          {static} - unmarshallServer()
      }
    }
  }
  

  namespace com.mysql.fabric {
    namespace proto.xmlrpc {
      interface com.mysql.fabric.proto.xmlrpc.XmlRpcMethodCaller {
          {abstract} + call()
          {abstract} + clearHeader()
          {abstract} + setHeader()
      }
    }
  }
  

  com.mysql.fabric.proto.xmlrpc.AuthenticatedXmlRpcMethodCaller .up.|> XmlRpcMethodCaller
  com.mysql.fabric.proto.xmlrpc.InternalXmlRpcMethodCaller .up.|> XmlRpcMethodCaller


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
