@startuml

title __JDBC4's Class Diagram__\n

  namespace testsuite {
    namespace regression {
      namespace jdbc4 {
        class testsuite.regression.jdbc4.ConnectionRegressionTest {
            + ConnectionRegressionTest()
            {static} + main()
            + testBug16634180()
            + testBug20685022()
            + testBug56122()
            + testBug62452()
            + testBug75168()
            - testBug62452WithConnection()
        }
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      namespace jdbc4 {
        class testsuite.regression.jdbc4.ExceptionSubclassesTest {
            + ExceptionSubclassesTest()
            + testBug17750877()
        }
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      namespace jdbc4 {
        class testsuite.regression.jdbc4.MetaDataRegressionTest {
            + MetaDataRegressionTest()
            {static} + main()
            + testBug17248345()
            + testBug19803348()
            + testBug20504139()
            + testBug20727196()
            + testBug44451()
            + testBug68307()
            + testBug69298()
            + testBug73775()
            + testReservedWords()
            - checkFunctionColumnTypeForBug68307()
            - checkGetFunctionColumnsForBug69298()
            - checkGetFunctionsForBug69298()
            - checkGetProcedureColumnsForBug69298()
            - checkGetProceduresForBug69298()
            - checkMetaDataInfoForBug17248345()
            - checkProcedureColumnTypeForBug68307()
            - checkReturnedColumnsForBug44451()
        }
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      namespace jdbc4 {
        class testsuite.regression.jdbc4.StatementRegressionTest {
            + StatementRegressionTest()
            {static} + main()
            + testBug68916()
            + testBug73163()
            + testBug78313()
            - subTestBug68916ForAllowMultiQueries()
            - subTestBug68916ForConcurrency()
            - subTestBug68916ForDontTrackOpenResources()
            - subTestBug68916ForHoldResultsOpenOverStatementClose()
            - subTestBug68916ForStandardConnection()
        }
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      namespace jdbc4 {
        class testsuite.regression.jdbc4.StatementRegressionTest.subTestBug68916ConcurrentTask {
            ~ closeOnCompletionIsOverriden : boolean
            ~ query : String
            ~ testConnection : Connection
            + call()
            ~ subTestBug68916ConcurrentTask()
        }
      }
    }
  }
  

  testsuite.regression.jdbc4.StatementRegressionTest +-down- testsuite.regression.jdbc4.StatementRegressionTest.subTestBug68916ConcurrentTask
  testsuite.regression.jdbc4.StatementRegressionTest.subTestBug68916ConcurrentTask .up.|> Callable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
