@startuml

title __PERF's Class Diagram__\n

  namespace testsuite {
    namespace perf {
      abstract class testsuite.perf.BasePerfTest {
          {static} ~ numberFormatter : NumberFormat
          {static} - T95 : double[]
          {static} - T99 : double[]
          - confidenceLevel : double
          - confidenceValue : double
          - intervalWidth : double
          - meanValue : double
          - numIterations : int
          - squareSumValue : double
          - sumValue : double
          - testValuesList : List<Double>
          - variationValue : double
          + BasePerfTest()
          + getMeanValue()
          # addResult()
          # doIterations()
          {abstract} # doOneIteration()
          # getCurrentConfidence()
          # getMarginOfError()
          # getStandardDeviationP()
          # reportResults()
          - getConfidenceLookup()
      }
    }
  }
  

  namespace testsuite {
    namespace perf {
      class testsuite.perf.LoadStorePerfTest {
          - largeResults : boolean
          - tableType : String
          - takeMeasurements : boolean
          - useColumnNames : boolean
          + LoadStorePerfTest()
          {static} + main()
          + setUp()
          + tearDown()
          + test1000Transactions()
          # doOneIteration()
          # warmUp()
      }
    }
  }
  

  namespace testsuite {
    namespace perf {
      class testsuite.perf.RetrievalPerfTest {
          {static} - NUM_ROWS : int
          {static} - NUM_TESTS : int
          + RetrievalPerfTest()
          {static} + main()
          + setUp()
          + testRetrievalCached()
          + testRetrievalHeap()
          + testRetrievalMyIsam()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
